### ISSUE TITLE
Error running the new version

### ISSUE THREAD

**Issue by simonweil** [prantlf/jsonlint#17]
When running as I did in the past I get the following error

```bash
$ jsonlint --diff --check
PATH/.nvm/versions/node/v19.6.0/lib/node_modules/@prantlf/jsonlint/lib/cli.js:503
    args = params.patterns || []
         ^

TypeError: Assignment to constant variable.
    at main (PATH/.nvm/versions/node/v19.6.0/lib/node_modules/@prantlf/jsonlint/lib/cli.js:503:10)
    at Object.<anonymous> (PATH/.nvm/versions/node/v19.6.0/lib/node_modules/@prantlf/jsonlint/lib/cli.js:543:1)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by prantlf** [comment]
Oh, I'm sorry. You probably sent the input using the pipe. There was a remnant of old code, which looked like as if there was an argument `--pattern` in the old code, but it has never worked, at least not in the fork. I removed the code in [14.0.1](https://github.com/prantlf/jsonlint/releases/tag/v14.0.1). I'm sorry for the trouble.

**Comment by simonweil** [comment]
Awesome, thanks for the fast turnaround @prantlf!
